# Generated by Django 4.1.3 on 2022-12-05 03:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_commentpost_post_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentpost",
            name="comment_id",
        ),
        migrations.AlterField(
            model_name="commentpost",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="commentpost",
            name="post_id",
            field=models.UUIDField(null=True),
        ),
    ]
