# Generated by Django 4.1.3 on 2022-12-05 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_commentpost_comment_id_alter_commentpost_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentpost",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
